// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duxqcadmvaybwuxqdajg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1eHFjYWRtdmF5Ynd1eHFkYWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzODA4NjUsImV4cCI6MjA4Mzk1Njg2NX0.O9kb-2RnDXu1uqfxXd08Di4OC3guFKe4sNgotnUgbVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});